version: "3.9"

services:
  postgres:
    image: postgres:17
    container_name: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: .env.prod
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"  # открыт внешний
    # ports:
    #   - "127.0.0.1:5432:5432"  # проброс только на localhost сервера 

  redis:
    image: redis:7
    container_name: redis
    restart: always

  backend:
    # build: ../django/nsinvest_backend
    build:
      context: https://github.com/lantemir/nsinvest_backend.git
      dockerfile: Dockerfile
    container_name: backend
    # volumes:
    #   - ../django/nsinvest_backend:/app
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - postgres
      - redis
    env_file: .env.prod
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python create_superuser.py &&
             daphne -b 0.0.0.0 -p 8000 backend.asgi:application"
    restart: always

  celery:
    # build: ../django/nsinvest_backend
    build:
      context: https://github.com/lantemir/nsinvest_backend.git
      dockerfile: Dockerfile
    container_name: celery
    # volumes:
    #   - ../django/nsinvest_backend:/app
    depends_on:
      - backend
      - redis
    env_file: .env.prod
    command: celery -A backend worker --loglevel=info
    restart: always

  celery-beat:
    # build: ../django/nsinvest_backend
    build:
      context: https://github.com/lantemir/nsinvest_backend.git
      dockerfile: Dockerfile
    container_name: celery_beat
    # volumes:
    #   - ../django/nsinvest_backend:/app
    depends_on:
      - backend
      - redis
    env_file: .env.prod
    command: celery -A backend beat --loglevel=info
    restart: always

  frontend:
    # build: ../next/nsinvest_front
    build:
      context: https://github.com/lantemir/nsinvest_front.git
      dockerfile: Dockerfile
    container_name: frontend
    # volumes:
    #   - ../next/nsinvest_front:/app
    depends_on:
      - backend
    env_file: .env.prod
    command: sh -c "npm install && npm run build && npm run start"
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/prod.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - /var/www/certbot:/var/www/certbot
      - /etc/letsencrypt:/etc/letsencrypt
      # - ../django/nsinvest_backend/staticfiles:/app/staticfiles
      # - ../django/nsinvest_backend/media:/app/media
    depends_on:
      - frontend
      - backend
    restart: always

volumes:
  postgres_data:
  static_volume:
  media_volume:
